import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";

import MyProvider from "@/components/provider/my-provider";
import ReduxProvider from "@/components/provider/redux-provider";
import Footer from "@/components/elements/Footer";
import NavigationBar from "@/components/elements/Navigationbar";

import { cn } from "@/lib/utils";

const rajdhani = Rajdhani({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "relative h-full font-sans antialiased",
          rajdhani.className
        )}
      >
        <ReduxProvider>
          <MyProvider>
            <NavigationBar />
            <main className="relative flex flex-col min-h-screen max-sm:mb-16 mt-16 sm:mt-28 ">
              <div className="flex-grow flex-1">{children}</div>
            </main>
            <Footer />
          </MyProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
