import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";

import MyProvider from "@/components/provider/my-provider";
import ReduxProvider from "@/components/provider/redux-provider";

const rajdhani = Rajdhani({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rajdhani.className}>
        <ReduxProvider>
          <MyProvider>{children}</MyProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
